language: haskell

env:
  matrix:
    - HPVER=2014.2.0.0 CABALVER=1.18
    - GHCVER=7.6.3 CABALVER=1.18
    - GHCVER=7.8.4 CABALVER=1.18
    - GHCVER=7.10.1 CABALVER=1.22
    - GHCVER=head CABALVER=head
  global:
    - UBUNTU_PKGS="libgtk-3-dev libcairo2-dev"
    - HEAD_DEPS="monoid-extras active statestack diagrams-solve diagrams-core diagrams-lib force-layout diagrams-contrib diagrams-svg diagrams-postscript diagrams-cairo diagrams-gtk diagrams-rasterific diagrams-canvas diagrams-pgf"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools Cabal"
    - CABAL_FLAGS="-fsvg -fpostscript -fcairo -fgtk -frasterific -fcanvas -fpgf"
    - SKIP_HADDOCK=1

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
